<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <CompatibilityFor>Ideology</CompatibilityFor>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <Deterministic>False</Deterministic>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <Deterministic>False</Deterministic>
    </PropertyGroup>
    <ItemGroup>
        <Content Include="..\..\Compatibility\Ideology\Common\**\*.*">
            <Link>Common\%(RecursiveDir)%(FileName)%(Extension)</Link>
        </Content>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\ToolkitUtils\ToolkitUtils.csproj" Private="false" ExcludeAssets="runtime" />
    </ItemGroup>
    <ItemGroup>
      <Reference Include="ToolkitCore">
        <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\ToolkitCore\1.6\Assemblies\ToolkitCore.dll</HintPath>
      </Reference>
      <Reference Include="TwitchLib.Client">
        <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\ToolkitCore\1.6\Assemblies\TwitchLib.Client.dll</HintPath>
      </Reference>
      <Reference Include="TwitchLib.Client.Models">
        <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\ToolkitCore\1.6\Assemblies\TwitchLib.Client.Models.dll</HintPath>
      </Reference>
      <Reference Include="TwitchToolkit">
        <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\TwitchToolkit2_0e\v1.6\Assemblies\TwitchToolkit.dll</HintPath>
      </Reference>
    </ItemGroup>
</Project>
