<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" />
        <PackageReference Include="PolySharp" />
        <PackageReference Include="Lib.Harmony" />
        <PackageReference Include="Krafs.Rimworld.Ref" />
        <PackageReference Include="NetEscapades.EnumGenerators" PrivateAssets="all" ExcludeAssets="runtime" />
    </ItemGroup>
    <ItemGroup>
      <Reference Include="Newtonsoft.Json">
        <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\ToolkitCore\Assemblies\Newtonsoft.Json.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="ToolkitCore">
        <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\ToolkitCore\1.6\Assemblies\ToolkitCore.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="TwitchLib.Api.Core.Enums">
        <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\ToolkitCore\1.6\Assemblies\TwitchLib.Api.Core.Enums.dll</HintPath>
      </Reference>
      <Reference Include="TwitchLib.Api.Core.Interfaces">
        <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\ToolkitCore\1.6\Assemblies\TwitchLib.Api.Core.Interfaces.dll</HintPath>
      </Reference>
      <Reference Include="TwitchLib.Client">
        <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\ToolkitCore\1.6\Assemblies\TwitchLib.Client.dll</HintPath>
      </Reference>
      <Reference Include="TwitchLib.Client.Enums">
        <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\ToolkitCore\1.6\Assemblies\TwitchLib.Client.Enums.dll</HintPath>
      </Reference>
      <Reference Include="TwitchLib.Client.Models">
        <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\ToolkitCore\1.6\Assemblies\TwitchLib.Client.Models.dll</HintPath>
      </Reference>
      <Reference Include="TwitchLib.Communication">
        <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\ToolkitCore\1.6\Assemblies\TwitchLib.Communication.dll</HintPath>
      </Reference>
      <Reference Include="TwitchToolkit">
        <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\TwitchToolkit\v1.6\Assemblies\TwitchToolkit.dll</HintPath>
        <Private>False</Private>
      </Reference>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Data.Traits.cs">
            <DependentUpon>Data.cs</DependentUpon>
        </Compile>
        <Compile Update="Data.PawnKinds.cs">
            <DependentUpon>Data.cs</DependentUpon>
        </Compile>
        <Compile Update="Data.Items.cs">
            <DependentUpon>Data.cs</DependentUpon>
        </Compile>
        <Compile Update="Data.Events.cs">
            <DependentUpon>Data.cs</DependentUpon>
        </Compile>
        <Compile Update="Data.Mods.cs">
            <DependentUpon>Data.cs</DependentUpon>
        </Compile>
        <Compile Update="Data.Surgeries.cs">
            <DependentUpon>Data.cs</DependentUpon>
        </Compile>
        <Compile Update="Data.Commands.cs">
            <DependentUpon>Data.cs</DependentUpon>
        </Compile>
        <Compile Update="Data.Reports.cs">
            <DependentUpon>Data.cs</DependentUpon>
        </Compile>
        <Compile Update="Data.Viewers.cs">
          <DependentUpon>Data.cs</DependentUpon>
        </Compile>
    </ItemGroup>

    <Import Project="..\ToolkitUtils.UX\ToolkitUtils.UX.projitems" Label="Shared" />

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <Deterministic>False</Deterministic>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <Deterministic>False</Deterministic>
    </PropertyGroup>

    <ItemGroup>
      <Reference Update="System">
        <Private>False</Private>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <Reference Update="System.Core">
        <Private>False</Private>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <Reference Update="System.Data">
        <Private>False</Private>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <Reference Update="System.Drawing">
        <Private>False</Private>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <Reference Update="System.IO.Compression.FileSystem">
        <Private>False</Private>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <Reference Update="System.Numerics">
        <Private>False</Private>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <Reference Update="System.Runtime.Serialization">
        <Private>False</Private>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <Reference Update="System.Xml">
        <Private>False</Private>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <Reference Update="System.Xml.Linq">
        <Private>False</Private>
      </Reference>
    </ItemGroup>
</Project>
