<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <OutputPath>..\..\$(RimWorldVersion)\Assemblies</OutputPath>
      <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
      <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <OutputPath>..\..\$(RimWorldVersion)\Assemblies\</OutputPath>
      <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
      <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <Deterministic>False</Deterministic>
      <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
      <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <Deterministic>False</Deterministic>
      <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
      <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>
    <PropertyGroup>
      <BaseOutputPath>C:\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\TwitchToolkitUtil2_0e\1.6\Assemblies</BaseOutputPath>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\ToolkitUtils\ToolkitUtils.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Compile Update="Events\PurchaseHandlerPatch.ResolveVariables.cs">
            <DependentUpon>PurchaseHandlerPatch.cs</DependentUpon>
        </Compile>
        <Compile Update="Events\PurchaseHandlerPatch.ResolveSimple.cs">
            <DependentUpon>PurchaseHandlerPatch.cs</DependentUpon>
        </Compile>
        <Compile Update="Events\PurchaseHandlerPatch.ItemCooldown.cs">
            <DependentUpon>PurchaseHandlerPatch.cs</DependentUpon>
        </Compile>
        <Compile Update="Events\PurchaseHandlerPatch.EventCooldown.cs">
            <DependentUpon>PurchaseHandlerPatch.cs</DependentUpon>
        </Compile>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\ToolkitUtils\ToolkitUtils.csproj" />
    </ItemGroup>
    <ItemGroup>
      <Reference Include="ToolkitCore">
        <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\ToolkitCore\1.6\Assemblies\ToolkitCore.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="TwitchLib.Client">
        <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\ToolkitCore\1.6\Assemblies\TwitchLib.Client.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="TwitchLib.Client.Models">
        <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\ToolkitCore\1.6\Assemblies\TwitchLib.Client.Models.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="TwitchToolkit">
        <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\TwitchToolkit2_0e\v1.6\Assemblies\TwitchToolkit.dll</HintPath>
        <Private>False</Private>
      </Reference>
    </ItemGroup>
    <ItemGroup>
      <Reference Update="System">
        <Private>False</Private>
      </Reference>
    </ItemGroup>
    <ItemGroup>
      <Reference Update="System.Core">
        <Private>False</Private>
      </Reference>
    </ItemGroup>
    <ItemGroup>
      <Reference Update="System.Data">
        <Private>False</Private>
      </Reference>
    </ItemGroup>
    <ItemGroup>
      <Reference Update="System.Drawing">
        <Private>False</Private>
      </Reference>
    </ItemGroup>
    <ItemGroup>
      <Reference Update="System.IO.Compression.FileSystem">
        <Private>False</Private>
      </Reference>
    </ItemGroup>
    <ItemGroup>
      <Reference Update="System.Numerics">
        <Private>False</Private>
      </Reference>
    </ItemGroup>
    <ItemGroup>
      <Reference Update="System.Runtime.Serialization">
        <Private>False</Private>
      </Reference>
    </ItemGroup>
    <ItemGroup>
      <Reference Update="System.Xml">
        <Private>False</Private>
      </Reference>
    </ItemGroup>
    <ItemGroup>
      <Reference Update="System.Xml.Linq">
        <Private>False</Private>
      </Reference>
    </ItemGroup>
</Project>
